language: node_js
node_js:
- 6.9.0
install:
- npm install
- npm run vendor:install
script:
- echo "building $TRAVIS_COMMIT"
- npm run build:release
after_success:
- mkdir -p ./dist
- tar -cvzf "./dist/web.tar.gz" ./public/
deploy:
  provider: releases
  api_key:
    secure: fhw0Q4DfRUreveSkVFHDHYsXFCKtHi2pUPxhrIgz6C2XHFaBj1OmomrPLMVtIy/TGyATDViQssC01rDEtsAIaQKdgzARvMEZyjNAVM+wjwNJ2Lt/P6RZmvsAxIVv0XHzPBCgaSN3EhLK458WGJO8/yJxQ7xjh9iVPodqqUKAzdI=
  file: ./dist/web.tar.gz
  on:
    repo: dadleyy/markhadley.la
