language: node_js
node_js:
- "6.9.0"
install:
- npm install
- npm run vendor:install
script:
- echo "building $TRAVIS_COMMIT"
- npm run build:release
after_success:
  - mkdir -p ./dist
  - tar -cvzf "./dist/markhadley-la.tar.gz" ./public/
deploy:
  provider: releases
  api_key:
    secure: Bu+vRcNBvq8GkpA0HHf+vp/mrUSjXxKejmLKE0VwOFO70+p2yrZhsEpmuHwWTgQJAVq2P+N05h6EAvsqq+ulARXyPgfq4gS4a8Lp7DHcEt0JlndutDDMaD4MKXTuRB8dcbUdiND7TklQHzTU9W7G2dYrZiCfTJ8TqBGdfkhoWmQ=
  file: dist/markhadley-la.tar.gz
  on:
    repo: dadleyy/markhadley.la
    tags: true
