language: node_js
node_js:
- '0.10'
install:
- gem install sass
- gem install bourbon
- gem install neat
- npm install bower -g
- npm install grunt-cli -g
- bower install
- npm install
script:
- echo "building $TRAVIS_COMMIT"
- grunt release
after_success:
- tar -cvzf "mhadley-$TRAVIS_COMMIT.tar.gz" ./public/
- curl --ftp-create-dirs -T "mhadley-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/artifacts/mhadley/$TRAVIS_COMMIT.tar.gz"
- curl --ftp-create-dirs -T "mhadley-$TRAVIS_COMMIT.tar.gz" -u $FTP_USER:$FTP_PASS
  "ftp://ftp.sizethreestudios.com/artifacts/mhadley/latest.tar.gz"
env:
  global:
  - secure: BwWon+qxmuP9gY0e/ypd7i5cYbSO3xOXZrIek1Wx9hcLz3U56/rmubhZA0DmuGOgncAkkGOSCIni57XPHhrHMfwJh1k33wQUBav24kTMlFscKBKMndgjIQSNtgYBMwelcr+qJ+pjZymXaDspBVd2yoZDGdoQiPtXvW5mBIp5XjY=
  - secure: NVSWygYPyezQAZNx2BBOePWZrWvi0rXvdmJl7dgtvgqCI2AMgMhxsUjBnjNm7Gi94802sC5pRwkvgXd5lBVklwy4k/FJQgQLgBvB3R8bJwZ77w2dXxJrZrjj/37DYAeUlenV+ilg/o3bAf0GxzXDRvf1wWX2BtWMYQDVpoS94xs=
  - secure: Zd2a6TSbLxnt0mkJwxV7bRn6kc3UD4ybWLchRAxeoo4hSDpVG5PL05oN34FBb4ugwxcdqb2TmU9EhlDZz1A3nVQialmGLAksYCcDrs3900RE0ysDwspT3tBXzLTyb9MTlzGyMs7Aud7RtytzGQ3OwwTvgtreJ6oMM9qWgnLgTMI=
  - secure: URlY5h+e7HjZEfEFTAGC+SSTC1F7SP1se16FaHoOMwVpq7rCzqwtPqHEqAPKHkKD8NP5I1LeBEUMvDHRgApNZzCF4xGVJCSrSNGeATudXfSmlnKgvrmz2NLOI3nTVvw0om4YEEv+Q6VCxOxmgNTSBIUpQqAhdfjjiDNADknpwxA=
  - secure: QnSpDRiTmTQGac78K89P1jxg/h7YQgR7V6+54scr4gaHO6dUfoAR8rr1YamzJxp0WSEmuKxy5136HLmFtwmK3fHBeWEVvNhWbT4uN+Xk04tTaHc3UOueMhZarqw+KivdbFc6jezt3OdDKfMgg15WDvFuJHtxZpH1de+Hca4zPe4=
  - secure: QDXguews8cxzBoqA9Fa2zw8QCbz8bLr5Nn2Yc+TV3QGL9JAYvab1SQTl45B9KegOFoeZkpGmyuL3qrAuKRmEJMKOpiu4AzWHvrazyxjYpzm11KzgOJIAkZig+T3qDympl4fGPftWbc82ChQYZ99j+g7ktnbCTc+Yew3ZIwWtv30=
